import { IntentCategory } from './intentParser';

export type ResponseType = 'text' | 'code' | 'email' | 'search' | 'system' | 'weather' | 'reminder' | 'translation' | 'joke';

export interface GeneratedResponse {
  text: string;
  type: ResponseType;
  data?: Record<string, unknown>;
}

const jokes = [
  "Why do programmers prefer dark mode? Because light attracts bugs! 🐛",
  "Why did the AI go to therapy? It had too many deep learning issues! 🤖",
  "What do you call a computer that sings? A Dell! 🎵",
  "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings! 😄",
  "How many programmers does it take to change a light bulb? None — that's a hardware problem! 💡",
];

const systemResponses: Record<string, string> = {
  open: "I'm initiating the launch sequence for that application. On a real system, I would use the OS process manager to open the requested application. The command would be executed with appropriate permissions.",
  volume: "Adjusting system volume. On a real system, I would interface with the audio subsystem to modify the master volume level.",
  screenshot: "Capturing screen. On a real system, I would use the display capture API to take a screenshot and save it to your Pictures folder.",
  brightness: "Adjusting display brightness. On a real system, I would interface with the display driver to modify backlight intensity.",
  shutdown: "Initiating shutdown sequence. On a real system, I would execute a graceful system shutdown after saving all open work.",
  default: "I've processed your system command. On a real system with full OS integration, I would execute this action directly. For now, I can describe exactly what steps would be taken.",
};

function extractCodeLanguage(input: string): string {
  const langs: Record<string, string> = {
    python: 'python', py: 'python', javascript: 'javascript', js: 'javascript',
    typescript: 'typescript', ts: 'typescript', html: 'html', css: 'css',
    java: 'java', cpp: 'cpp', 'c++': 'cpp', rust: 'rust', go: 'golang',
  };
  const lower = input.toLowerCase();
  for (const [key, val] of Object.entries(langs)) {
    if (lower.includes(key)) return val;
  }
  return 'javascript';
}

function generateCodeSample(input: string, lang: string): string {
  const samples: Record<string, string> = {
    python: `# FRIDAY Generated Code
def main():
    """
    Generated by FRIDAY AI Assistant
    Task: ${input.slice(0, 50)}...
    """
    print("Hello from FRIDAY!")
    
    # Your implementation here
    data = []
    
    for item in data:
        process(item)
    
    return True

def process(item):
    """Process individual items"""
    # Add your logic here
    pass

if __name__ == "__main__":
    main()`,
    javascript: `// FRIDAY Generated Code
// Task: ${input.slice(0, 50)}...

async function main() {
  console.log("Hello from FRIDAY!");
  
  // Your implementation here
  const data = [];
  
  for (const item of data) {
    await processItem(item);
  }
  
  return true;
}

async function processItem(item) {
  // Add your logic here
  return item;
}

main().catch(console.error);`,
    typescript: `// FRIDAY Generated TypeScript Code
// Task: ${input.slice(0, 50)}...

interface DataItem {
  id: string;
  value: unknown;
}

async function main(): Promise<void> {
  console.log("Hello from FRIDAY!");
  
  const data: DataItem[] = [];
  
  for (const item of data) {
    await processItem(item);
  }
}

async function processItem(item: DataItem): Promise<DataItem> {
  // Add your logic here
  return item;
}

main().catch(console.error);`,
    html: `<!DOCTYPE html>
<!-- FRIDAY Generated HTML -->
<!-- Task: ${input.slice(0, 50)}... -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FRIDAY Generated Page</title>
  <style>
    body { font-family: sans-serif; margin: 0; padding: 20px; }
    .container { max-width: 800px; margin: 0 auto; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Generated by FRIDAY</h1>
    <p>Your content here</p>
  </div>
</body>
</html>`,
  };
  return samples[lang] || samples['javascript'];
}

export function generateResponse(input: string, intent: IntentCategory): GeneratedResponse {
  const lower = input.toLowerCase();

  switch (intent) {
    case 'SYSTEM_CONTROL': {
      let responseText = systemResponses.default;
      if (lower.includes('open') || lower.includes('launch')) responseText = systemResponses.open;
      else if (lower.includes('volume')) responseText = systemResponses.volume;
      else if (lower.includes('screenshot')) responseText = systemResponses.screenshot;
      else if (lower.includes('brightness')) responseText = systemResponses.brightness;
      else if (lower.includes('shutdown') || lower.includes('restart')) responseText = systemResponses.shutdown;
      return {
        text: `⚡ System Command Acknowledged\n\n${responseText}\n\nNote: Full OS integration requires the FRIDAY desktop agent to be installed and running.`,
        type: 'system',
      };
    }

    case 'FILE_MANAGEMENT': {
      return {
        text: `📁 File System Operation\n\nI've analyzed your file management request. On a system with full integration, I would:\n\n1. Scan the specified directories\n2. Apply your search criteria\n3. Return matching results with full paths\n4. Allow you to perform operations on the results\n\nFor now, I can help you plan the file operation or write a script to automate it.`,
        type: 'system',
      };
    }

    case 'WEB_SEARCH': {
      const query = input.replace(/search (for |the web for |online for )?/i, '').replace(/\?$/, '');
      return {
        text: `Searching for: "${query}"`,
        type: 'search',
        data: {
          query,
          results: [
            {
              title: `${query} - Comprehensive Overview`,
              snippet: `A detailed overview of ${query}, covering key concepts, recent developments, and practical applications in today's context.`,
              source: 'encyclopedia.example.com',
            },
            {
              title: `Latest Updates on ${query}`,
              snippet: `Stay up to date with the most recent news and developments related to ${query}. Expert analysis and insights included.`,
              source: 'news.example.com',
            },
            {
              title: `How to understand ${query} - Complete Guide`,
              snippet: `Step-by-step guide to understanding ${query}. Includes examples, tutorials, and best practices for beginners and experts.`,
              source: 'guide.example.com',
            },
          ],
        },
      };
    }

    case 'COMMUNICATION': {
      const toMatch = input.match(/to\s+([A-Za-z\s]+?)(?:\s+about|\s+regarding|\s+re:|\s*$)/i);
      const subjectMatch = input.match(/about\s+(.+?)(?:\s*$)/i);
      const recipient = toMatch ? toMatch[1].trim() : '[Recipient]';
      const subject = subjectMatch ? subjectMatch[1].trim() : '[Subject]';
      return {
        text: `Drafting email for you...`,
        type: 'email',
        data: {
          to: recipient,
          subject: `Re: ${subject}`,
          body: `Dear ${recipient},\n\nI hope this email finds you well.\n\nI am writing to you regarding ${subject}.\n\n[Your message here]\n\nPlease let me know if you have any questions or need further information.\n\nBest regards,\n[Your Name]`,
        },
      };
    }

    case 'CONTENT_CREATION': {
      if (lower.includes('code') || lower.includes('script') || lower.includes('program') || lower.includes('function')) {
        const lang = extractCodeLanguage(input);
        const code = generateCodeSample(input, lang);
        return {
          text: `Here's the code I generated for you:`,
          type: 'code',
          data: { language: lang, code },
        };
      }
      return {
        text: `✨ Content Creation\n\nI've started working on your content request. Here's what I'll create:\n\n**Title:** ${input.replace(/create|make|write|generate|design/gi, '').trim()}\n\n**Structure:**\n• Introduction\n• Main Content (3-5 sections)\n• Conclusion\n• Call to Action\n\nWould you like me to proceed with a specific format or style? I can create presentations, documents, reports, or creative content.`,
        type: 'text',
      };
    }

    case 'WEATHER': {
      return {
        text: `🌤️ Weather Information\n\nI'd love to give you real-time weather data! For accurate weather information, I would connect to a weather API using your location.\n\n**Simulated Forecast:**\n• Today: Partly cloudy, 24°C (75°F)\n• Tomorrow: Sunny, 27°C (81°F)\n• Day after: Light rain, 20°C (68°F)\n\nFor real weather data, I would need location access and an API connection.`,
        type: 'text',
      };
    }

    case 'REMINDER': {
      const timeMatch = input.match(/at\s+(\d{1,2}(?::\d{2})?\s*(?:am|pm)?)/i);
      const time = timeMatch ? timeMatch[1] : 'the specified time';
      return {
        text: `⏰ Reminder Set\n\nI've noted your reminder for ${time}.\n\nOn a fully integrated system, I would:\n• Add this to your system calendar\n• Set a notification alert\n• Send you a reminder message\n• Optionally sync with your mobile device\n\nYour reminder has been logged in our conversation memory.`,
        type: 'text',
      };
    }

    case 'TRANSLATION': {
      const langMatch = input.match(/to\s+(telugu|hindi|english|spanish|french|german|japanese|chinese)/i);
      const targetLang = langMatch ? langMatch[1] : 'the target language';
      return {
        text: `🌐 Translation\n\nTranslating to ${targetLang}...\n\nFor accurate translations, I would use a professional translation API. I support:\n• English ↔ Telugu\n• English ↔ Hindi\n• And 100+ other language pairs\n\nPlease provide the text you'd like translated and I'll do my best to assist!`,
        type: 'text',
      };
    }

    case 'JOKE': {
      const joke = jokes[Math.floor(Math.random() * jokes.length)];
      return { text: joke, type: 'joke' };
    }

    default: {
      const responses = [
        `I understand you're asking about "${input.slice(0, 60)}${input.length > 60 ? '...' : ''}". Let me help you with that.\n\nAs your AI assistant, I'm here to assist with tasks, answer questions, control your system, search the web, create content, and much more. What specific aspect would you like me to focus on?`,
        `That's an interesting request! I'm processing your query about "${input.slice(0, 50)}${input.length > 50 ? '...' : ''}".\n\nI can help you with system control, file management, web searches, writing emails, generating code, and general assistance. How would you like to proceed?`,
        `I've analyzed your message. Here's my response:\n\n"${input.slice(0, 80)}${input.length > 80 ? '...' : ''}"\n\nI'm FRIDAY, your intelligent assistant. I'm continuously learning and improving. Is there a specific task you'd like me to help you accomplish?`,
        `Understood! I'm here to assist you. Regarding "${input.slice(0, 60)}${input.length > 60 ? '...' : ''}" — I can provide information, execute tasks, or help you plan your approach. What would be most helpful?`,
      ];
      return {
        text: responses[Math.floor(Math.random() * responses.length)],
        type: 'text',
      };
    }
  }
}
